name: Deploy Dev

on:
  workflow_dispatch:
    inputs:
      components:
        description: The associated Terraform components for the service
        type: string
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ api,drs,dms ]
      fail-fast: true
      max-parallel: 1
    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4

      - name: Echo
        run: echo ${{ matrix.component }}

      - name: Apply
        uses: ./.github/workflows/deploy-dev-apply.yaml@master
        with:
          component: ${{ matrix.component }}

