name: Deploy Live

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  plan:
    strategy:
      matrix:
        component: [ api,drs,dms ]
      fail-fast: true
      max-parallel: 1

    uses: ./reusable-deploy.yaml@master
    with:
      component: ${{ matrix.component }}




