name: Manage NonProd RDS Clusters

on:
  workflow_dispatch:
    inputs:
      action:
        description: Whether to start or stop the RDS instance/s
        type: choice
        options:
          - start
          - stop
  # schedule: 
  #   - cron: "*/5 * * * *"

permissions:
  id-token: write
  contents: write

jobs:
  get-nonprod-clusters:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-nonprod-clusters.outputs.matrix }}
    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4

      - name: echo
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo ${{ inputs.action }}

      - name: echo 
        if: ${{ github.event_name == 'schedule' }}
        run: echo "hi"
